project:
  type: book
  output-dir: docs
  # resources:
    # - search_console.html

book:
  repo-url: https://github.com/paithiov909/textvis-recipes
  site-url: https://paithiov909.github.io/textvis-recipes
  title: "Cookbook to Draw KHCoder-like Visualizations Using R"
  author: "Akiru Kato"
  description: "RによるKH Coder風の可視化のレシピ集"
  cover-image: cover.png
  cover-image-alt: "Cookbook to Draw KHCoder-like Visualizations Using R"
  image: cover.png
  favicon: favicon.ico
  open-graph:
    locale: ja
  twitter-card:
    card-style: summary
  chapters:
    - index.qmd
    - preprocessing.qmd
    - plot-words.qmd
    - references.qmd
  comments:
    giscus:
      repo: paithiov909/textvis-recipes
      repo-id: R_kgDOLWfubw
      category: Announcements
      category-id: DIC_kwDOLWfub84Cdg5_
      mapping: pathname
      reactions-enabled: true
      input-position: top
      loading: lazy
      language: ja

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    mainfont: |
      -apple-system, "BlinkMacSystemFont", "Helvetica Neue", Helvetica, "Arial", "ヒラギノ角ゴ ProN W3", "Hiragino Kaku Gothic ProN", "メイリオ", Meiryo, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"
    code-fold: true

knitr:
  opts_chunk:
    tidy: "styler"
    collapse: true
    comment: "#>"
