version: "3.9"
name: khcoder
services:
  app:
    container_name: khcoder-app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/root/workspace
    networks:
      - kh-net
    environment:
      ENV LANGUAGE: ja_JP.UTF-8
      ENV LANG: ja_JP.UTF-8
      ENV LC_ALL: ja_JP.UTF-8
      ENV TZ: Asia/Tokyo
  db:
    image: mysql:5.7
    container_name: khcoder-mysql-5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: khcoder
      MYSQL_DATABASE: khcoder
      MYSQL_USER: khcoder
      MYSQL_PASSWORD: khcoder
    networks:
      - kh-net

networks:
  kh-net:
    driver: bridge
